version: '3.9'

services:
  db:
    image: postgres:alpine
    container_name: integration_openproject_db
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud

  redis:
    image: redis:alpine
    container_name: integration_openproject_redis
    restart: always
    ports:
      - "6379:6379"

  nextcloud:
    image: nextcloud:apache
    container_name: integration_openproject_nc
    restart: always
    network_mode: "host"
    volumes:
      - nextcloud:/var/www/html
      - ${APP_DIR:-./../integration_openproject}:/var/www/html/custom_apps/integration_openproject
    environment:
      - POSTGRES_HOST=localhost:5433
      - REDIS_HOST=localhost
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:apache
    container_name: integration_openproject_cron
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
