# SPDX-FileCopyrightText: 2025 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1
SPDX-PackageName = "integration_openproject"
SPDX-PackageSupplier = "Nextcloud <info@nextcloud.com>"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud/integration_openproject"

[[annotations]]
path = ["l10n/*.js", "l10n/*.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 Nextcloud translators"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [".tx/config"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [".tx/backport"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022-2024 Jankari Tech Pvt. Ltd."
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["composer.json", "composer.lock"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022-2025 Jankari Tech Pvt. Ltd., 2022 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["package-lock.json", "package.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2025 Nextcloud GmbH and Nextcloud contributors, 2022-2024 Jankari Tech Pvt. Ltd."
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["tests/jest/components/__snapshots__/AdminSettings.spec.js.snap", "tests/jest/components/__snapshots__/OAuthConnectButton.spec.js.snap", "tests/jest/components/__snapshots__/PersonalSettings.spec.js.snap", "tests/jest/components/tab/__snapshots__/EmptyContent.spec.js.snap", "tests/jest/components/tab/__snapshots__/SearchInput.spec.js.snap", "tests/jest/components/tab/__snapshots__/WorkPackage.spec.js.snap", "tests/jest/components/admin/__snapshots__/FieldValue.spec.js.snap", "tests/jest/components/admin/__snapshots__/FormHeading.spec.js.snap", "tests/jest/components/admin/__snapshots__/TextInput.spec.js.snap", "tests/jest/views/__snapshots__/CreateWorkpackageModal.spec.js.snap", "tests/jest/views/__snapshots__/Dashboard.spec.js.snap", "tests/jest/views/__snapshots__/LinkMultipleFilesModal.spec.js.snap", "tests/jest/views/__snapshots__/ProjectsTab.spec.js.snap"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022-2025 Jankari Tech Pvt. Ltd., 2022-2023 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["tests/jest/fixtures/availableProjectAssigneesResponse.json", "tests/jest/fixtures/availableProjectOptions.json", "tests/jest/fixtures/formValidationResponseRequiredType.json", "tests/jest/fixtures/notificationsResponse.json", "tests/jest/fixtures/openprojectAvailableProjectResponse.json", "tests/jest/fixtures/openprojectAvailableProjectResponseAfterSearch.json", "tests/jest/fixtures/workpackageFormValidationProjectSelectedResponse.json", "tests/jest/fixtures/workpackageFormValidationTypeChanged.json", "tests/jest/fixtures/workPackageObjectsInSearchResults.json", "tests/jest/fixtures/workPackageSearchReqResponse.json", "tests/jest/fixtures/workPackagesSearchResponse.json", "tests/jest/fixtures/workPackagesSearchResponseNoAssignee.json", "tests/jest/fixtures/workPackageSuccessfulCreationResponse.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022-2024 Jankari Tech Pvt. Ltd."
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["img/app.svg", "img/app-dark.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018-2024 Google LLC"
SPDX-License-Identifier = "LicenseRef-OpenProjectTrademarks"

[[annotations]]
path = ["img/bell-ring.svg", "img/bell-ring-dark.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2012-2024 OpenProject GmbH"
SPDX-License-Identifier = "Apache-2.0"
