services:
  keycloak-db:
    image: postgres:13
    restart: always
    networks:
      - nc-op
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    restart: always
    command:
      [
        'start-dev',
        '--proxy edge',
        '--spi-connections-http-client-default-disable-trust-manager=true',
        '--import-realm'
      ]
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_SCHEMA: public
      KC_HOSTNAME: keycloak.local
      KC_FEATURES: preview
      KC_TRANSACTION_XA_ENABLED: false
    networks:
      - nc-op
    volumes:
      - ./opnc-realm.json:/opt/keycloak/data/import/opnc-realm.json
      - step:/step:ro
      - keycloakdata:/opt/keycloak/data/
    labels:
      traefik.enable: true
      traefik.http.routers.keycloak.rule: Host(`keycloak.local`)
      traefik.http.routers.keycloak.entrypoints: websecure
    depends_on:
      - keycloak-db
      - traefik

volumes:
  keycloakdata:
